In [14]:
a=[]
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter number:"))
    a.append(val)
b = np.array(a)
b

Enter size: 4
Enter number: 5
Enter number: 7
Enter number: 8
Enter number: 0


array([5, 7, 8, 0])

In [16]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [17]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a = np.ones(3)
a

array([1., 1., 1.])

In [19]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
a.shape

(3, 4)

In [21]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
a = np.diag([1,56,89,700])
a

array([[  1,   0,   0,   0],
       [  0,  56,   0,   0],
       [  0,   0,  89,   0],
       [  0,   0,   0, 700]])

In [24]:
a = np.random.randint(1,10,3)
a

array([4, 5, 5])

In [25]:
a = np.random.rand(5)
a

array([0.1487211 , 0.83705828, 0.28533945, 0.81026681, 0.79325675])

In [26]:
a = np.random.randn(5)
a

array([ 1.43328975, -0.2767978 ,  0.90413628, -0.59638674,  0.97884323])

In [5]:
import numpy as np

In [6]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
a =np.arange(1,5)
b =np.arange(5,9)
c =np.arange(9,13)

In [10]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])